# Generated by Django 2.0.7 on 2018-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('capital', models.CharField(max_length=120)),
                ('currency', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
